In [1]:
import numpy as np

In [9]:
#creation - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "string", True])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

#2d list -> array
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr3, type(arr3), arr3.dtype, arr3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'string' 'True'] <class 'numpy.ndarray'> <U21 (7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [15]:
#creation - using built in methods (from scratch)
np1 = np.zeros((2, 3), dtype="int64") #prefill with 0s, 2d
print(np1, np1.shape)

np2 = np.ones((6, )) #bydefault - in float
print(np2, np2.shape)

np3 = np.full((4, 3), 10) #prefill with val
print(np3, np3.shape)

np4 = np.eye(3) #identity matrix of size 3 (sq matrix)
print(np4, np4.shape)

np5 = np.arange(1, 10, 2) #range elements - (start, end, step)
print(np5, np5.shape)

np6 = np.linspace(1, 100, 3) #evenly spaced array
print(np6, np6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1. 1.] (6,)
[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]] (4, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)


In [ ]:
#Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape) #dimensions = m x n
print(arr.size) #total elems
print(arr.dtype) #data type of elems
print(arr.ndim) #total no of dimension - 1d(1), 2d(2)...

#type casting (astype() & dtype="")
float_arr = arr.astype(np.float64) #convert int64 -> float64
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [23]:
#Operations on arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2)) #reshaping array (size should be same)  - (x, y) -> (y, x)
print(reshaped, reshaped.shape)

flattened = arr.flatten() # flattens the array - 2D => 1D
print(flattened, flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [27]:
#Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[3])
print(arr[2])

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[0][2])
print(arr2d[1][0])

4
3
3
4


In [ ]:
#Fancy Indexing - accessing multiple idxs (vectorization)
arr = np.array([1, 2, 3, 4, 5])
idx = [1, 2, 4]
print(arr[idx])

[2 3 5]


In [32]:
#Boolean Indexing - filtering on base of a condition
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2]) #condition passed 
print(arr[arr % 2 == 0])

[3 4 5]
[2 4]


In [36]:
#Slicing - [start : end : step]
arr = np.array([1, 2, 3, 4, 5])
print(arr[:])
print(arr[1:])
print(arr[:4])
print(arr[0:3])
print(arr[0:4:2])

[1 2 3 4 5]
[2 3 4 5]
[1 2 3 4]
[1 2 3]
[1 3]


In [45]:
#Copy vs View
nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 100
print(nums)
print(sub_list) #changes doesn't reflect in org list

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 100
print(arr)
print(sub_arr) #changes reflect in org array

#copy in arrays
copy_arr = arr[2:4].copy() #copy is created
print(copy_arr)
copy_arr[0] = 200
print(copy_arr)
print(arr)


[2, 3]
[1, 2, 3, 4, 5]
[100, 3]
[2 3]
[  1 100   3   4   5]
[100   3]
[3 4]
[200   4]
[  1 100   3   4   5]
